version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: walletwise_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: walletwise_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/walletwise
      - JWT_SECRET=walletwisesupersecretjwtkeyforhackathon2026
      - NODE_ENV=production
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: walletwise_web
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend

volumes:
  mongodb_data:
